select * from customer limit 20
--total revenue generated by male and female
select gender,sum(purchase_amount) as revenue
from customer group by gender
--customer used discount but still spent more than average amount
select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)
-- top 5 products with the highest average rating
SELECT item_purchased,
       ROUND(CAST(AVG(review_rating) AS numeric),2) AS "Average Product Rating" 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
--compare the avg purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2)  from customer
where shipping_type in ('Standard','Express') group by shipping_type
 --do subscribe customers spend more ?compare average spend and total revenue between subcribers and non-subscribers
 select subscription_status,
 count(customer_id) as total_customers,Round(avg(purchase_amount),2) 
 as avg_spend,round(sum(purchase_amount),2) as total_revenue from customer group by subscription_status
 order by total_revenue ,avg_spend desc;
 --which 5 products have the highest percentage of purchase with discounts applied
SELECT item_purchased,
ROUND(100 * sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/count(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--segment customers into new,returning and loyal based on their
--total number of previous purchases and show the count of each segment.
with customer_type as 
(select customer_id,previous_purchases,
CASE
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment

--what are the top 3 most purchased products within each category?
with item_counts as (select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id)desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts

--are customers who are repeat buyers(more than 5 previous purchases)also likely to subscribr?
select subscription_status,count(customer_id)  as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status
--what is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;